### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by mufeili** [facebookresearch/visdom#304]
Hello, I am working with Python 3.5.2 on macOS using Pyenv. When I tried the following example:
```
import matplotlib.pyplot as plt
plt.plot([1, 23, 2, 4])
plt.ylabel('some numbers')
viz.matplot(plt)
```
I encountered the following warning:

>   File "<stdin>", line 1, in <module>
  File "/Users/MufeiLi/.pyenv/versions/3.5.2/lib/python3.5/site-packages/visdom-0.1.7.2-py3.5.egg/visdom/__init__.py", line 482, in matplot
    opts['height'] = 1.4 * int(re.search('height\="([0-9]*)pt"', svg).group(1))
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by JackUrb** [comment]
Hi @mufeili - We're still working on getting our matplotlib integration down fully, and this bug seems to come out of one of the ways we were getting things to work. I'll investigate a fix!

**Comment by lvdmaaten** [comment]
It appears that not all versions of matplotlib produce the same SVG (given the same input). 

@mufeili To help me debug this, could you add a `print(svg)` in `visdom/init.py:481` and send me a Gist containing the output of that print?

**Comment by mufeili** [comment]
Hi @lvdmaaten , you may find the result here [result of print(svg)](https://gist.github.com/mufeili/0ca5f9c61c769db57c12bddd7a4297de). The result is from Python 3.6 installed by Anaconda rather than what I described initially due to my attempts to fix it myself. Thanks.

**Comment by JackUrb** [comment]
Ah @lvdmaaten we're missing catching a decimal in the regex!

**Comment by lvdmaaten** [comment]
Yep :)
